name: CI EvilShell
on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4

      - name: Install build dependencies
        run: |
          python -m pip install -r requirements.txt
          python3 setup.py install
          
      - name: Additional libraries for testing
        run: pip install testfixtures coverage pexpect paramiko
